nsl = 99
ndl = 99
ntrg = 99
box = 32
origin = [1,2,3]
kernel = 0 
pbc = 0
seed = 0
eps = 1e-4
max = 2000
direct = false
verify = false
convergence = true
distType = 2
distParam = [-1.0, 0.5]
random = true
wall = false

