nsl = 199
ndl = 199
ntrg = 199
box = 60
origin = [1,2,3]
lognormal = [-1,0.5]
kernel = 0 
pbc = 0
seed = 0
eps = 1e-4
max = 2000
direct = false
verify = false
convergence = true
random = true
wall = false

